-- Create properties table
CREATE TABLE IF NOT EXISTS public.properties (
    id SERIAL PRIMARY KEY,
    type TEXT NOT NULL,
    rooms INTEGER,
    bedrooms INTEGER,
    surface DECIMAL,
    city TEXT,
    quartier TEXT,
    price BIGINT,
    title TEXT,
    description TEXT,
    highlights TEXT[],
    url TEXT,
    gradient TEXT,
    prestige BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON public.properties
    FOR SELECT USING (true);

-- Seed properties data
INSERT INTO public.properties (id, type, rooms, bedrooms, surface, city, quartier, price, title, description, highlights, url, gradient, prestige)
VALUES
(170, 'Appartement', 3, 2, 91.95, 'Le Cannet', 'Le Cannet', 413000, 'Grand 3 pièces — Parking & Cave', 'Spacieux appartement de 91.95 m², idéalement situé proche des commerces, à 10 minutes du centre de Cannes. Grande entrée, dressings, cuisine équipée fermée, vaste séjour salon.', ARRAY['Parking', 'Cave', 'Proche Cannes'], 'https://www.agencerossicroisette.com/vente/9-le-cannet/appartement/170-le-cannet-grand-3-pieces-parking-et-cave', 'grad-1', false),
(169, 'Appartement', 1, 0, 20, 'Cannes', 'Basse Californie', 195000, 'Studio — Cave, Parking & Terrasse', 'Studio de 20 m² dans une charmante copropriété proche des commerces. Cuisine équipée, belle terrasse de 12 m², salle de douche. Parking et cave inclus.', ARRAY['Terrasse 12m²', 'Parking', 'Cave'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/169-cannes-basse-californie-studio-cave-parking-terrasse', 'grad-2', false),
(163, 'Appartement', 3, 2, 47, 'Cannes', 'La Croisette', 1260000, '3 pièces Croisette — Balcon, Vue Mer, Rénové', 'Sur la célèbre Croisette, entièrement rénové avec des prestations modernes. 3ᵉ étage, belle luminosité, terrasse de 7 m² avec vue mer partielle.', ARRAY['Vue mer', 'Terrasse 7m²', 'Rénové', 'Croisette'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/163-a-vendre-cannes-croisette-3-pieces-2-chambres-balcon-renove', 'grad-3', true),
(156, 'Appartement', 2, 1, 36.16, 'Cannes', 'La Croisette', 760000, '2 pièces Croisette 1ère ligne — Vue Panoramique Mer', 'Croisette première ligne, magnifique 2 pièces de 36 m². Hall d\'entrée avec dressing, cuisine séparée équipée, séjour donnant sur terrasse de 7 m², vue panoramique sur la baie.', ARRAY['Vue mer panoramique', 'Terrasse 7m²', '1ère ligne', 'Parking'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/156-cannes-croisette-vue-panoramique-mer', 'grad-4', true),
(154, 'Appartement', 3, 2, 75, 'Cannes', 'La Croisette', 1590000, '3 pièces Croisette — Rénové, Parking, Terrasse', 'Magnifique 3 pièces de 75 m² sur la célébre Croisette. Proche des plages, restaurants, Palais des Festivals. Rénové, parking extérieur inclus.', ARRAY['Croisette', 'Terrasse', 'Parking', 'Rénové'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/154-a-vendre-cannes-croisette-3-pieces-2-chambres-renove-parking-exterieur-terrasse', 'grad-5', true),
(153, 'Appartement', 3, 2, 57, 'Cannes', 'Basse Californie', 450000, '3 pièces — Balcon, Terrasse & Cave', 'Secteur Basse Californie, à quelques minutes du centre-ville, des commerces, de la plage et de la Croisette. 3 pièces partiellement rénové avec balcon et terrasse.', ARRAY['Balcon', 'Terrasse', 'Cave', 'Basse Californie'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/153-a-vendre-cannes-3-pieces-2-chambres-renove-balcon-terrasse-cave', 'grad-6', false),
(152, 'Appartement', 4, 3, 157.9, 'Cannes', 'Centre-Ville', 1375000, '4 pièces Art-Déco — 157 m², Rénové', 'À quelques minutes à pied des plages et du centre-ville, magnifique 4 pièces Art-Déco de 157.9 m². Double séjour, salle à manger, cuisine équipée.', ARRAY['157 m²', 'Art-Déco', 'Rénové', 'Grand Volume'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/152-a-vendre-cannes-art-deco-4p-3-chambres-renove', 'grad-1', true),
(151, 'Appartement', 3, 2, 74.37, 'Cannes', 'Basse Californie', 780000, '3 pièces — Terrasse Vue Mer, Garage & Cave', 'Dans un écrin de verdure, proche des plages, dans une très belle résidence avec gardien. Appartement entièrement rénové, grand séjour, terrasse avec vue mer.', ARRAY['Vue mer', 'Terrasse', 'Garage', 'Cave', 'Gardien'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/151-vente-cannes-basse-californie-3pces-terrasse-vue-mer-garage-cave', 'grad-2', false),
(150, 'Maison', 7, 4, 315, 'Cannes', 'La Californie', 6970000, 'Villa-Appartement 315 m² — Vue Mer, Parc 2 ha', 'Villa-appartement lumineuse de 7 pièces dans le secteur de la Californie. Implantée dans un parc paysager de 2 hectares, rénovée par un architecte de renom. Vue panoramique.', ARRAY['315 m²', 'Vue mer panoramique', 'Parc 2 ha', 'Architecte'], 'https://www.agencerossicroisette.com/vente/1-cannes/maison/150-a-vendre-cannes-villa-appartement-vue-mer-315-m2', 'grad-3', true),
(149, 'Appartement', 4, 3, 110, 'Cannes', 'La Croisette', 2580000, '4 pièces Croisette — Dernier Étage, Vue Mer', 'Un appartement rénové d\'exception sur la Croisette. 4 pièces de 110 m² perché au dernier étage, vue imprenable sur la mer. Vaste séjour baigné de lumière avec terrasse.', ARRAY['Dernier étage', 'Vue mer', 'Croisette', '110 m²', 'Terrasse'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/149-a-vendre-cannes-croisette-4-p-dernier-etage-vue-mer-panoramique', 'grad-4', true),
(148, 'Appartement', 5, 4, 118, 'Cannes', 'Roi Albert', 2480000, '5 pièces Roi Albert — Vue Mer Panoramique', 'Magnifique propriété offrant une vue panoramique sur la Méditerranée. Entièrement rénové avec des matériaux de haute qualité. 5 pièces spacieuses dans une résidence de prestige.', ARRAY['Vue mer panoramique', '118 m²', 'Matériaux luxe', 'Rénové'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/148-a-vendre-cannes-roi-albert-5-pieces-vue-mer', 'grad-5', true),
(147, 'Appartement', 4, 3, 92, 'Cannes', 'La Californie', 2580000, '4 pièces Californie — 6ème Étage, Vue Mer Panoramique', 'Dans une belle résidence de standing, 4 pièces de 92 m² au 6ème étage with vue mer panoramique. 3 chambres en suite, cuisine ouverte, belle terrasse.', ARRAY['6ème étage', 'Vue mer', '3 suites', 'Californie', 'Terrasse'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/147-a-vendre-superbe-4-pieces-vue-mer-panoramique-secteur-californie', 'grad-6', true),
(146, 'Appartement', 5, 6, 219.58, 'Cannes', 'Vieux Port', 3300000, 'Penthouse Vieux Port — 107 m² + 105 m² Terrasse', 'L\'exclusivité ultime de la French Riviera. Penthouse au Vieux Port de Cannes, rénové avec goût. 107 m² + 105 m² de terrasse, vue mer extraordinaire sur la Méditerranée.', ARRAY['Penthouse', 'Terrasse 105m²', 'Vue mer', 'Vieux Port', 'Exclusivité'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/146-a-vendre-cannes-penthouse-107-m2-vue-panoramique-mer', 'grad-1', true),
(145, 'Appartement', 3, 2, 70, 'Cannes', 'La Croisette', 2380000, '3 pièces Croisette Traversant — Vue Mer Panoramique', 'Superbe 3 pièces de 70 m² traversant rénové dans une résidence de standing sur la Croisette. Pièce à vivre avec cuisine ouverte, 2 belles chambres en suite.', ARRAY['Vue mer panoramique', 'Traversant', 'Croisette', 'Rénové', '2 suites'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/145-a-vendre-cannes-croissette-3-p-traversant-vue-mer-panoramique', 'grad-2', true),
(144, 'Appartement', 4, 3, 100, 'Cannes', 'Palm Beach', 1980000, '4 pièces Palm Beach — Vue Mer, Piscine', 'Magnifique 4 pièces au 3ème étage dans une résidence avec piscine, refait à neuf au style moderne. Secteur prisé du Palm Beach avec vue mer, traversant.', ARRAY['Vue mer', 'Piscine', 'Palm Beach', 'Rénové', '100 m²'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/144-a-vendre-cannes-secteur-palm-beach-vue-mer-4-pieces', 'grad-3', true),
(143, 'Villa', 9, 6, 300, 'Cannes', 'La Californie', 6970000, 'Villa Californie — 300 m², Piscine, Vue Îles de Lérins', 'Villa d\'exception de 300 m² dans le prestigieux quartier de la Californie. Panorama à couper le souffle sur les Îles de Lérins et la mer. Piscine, terrain.', ARRAY['300 m²', 'Piscine', 'Vue mer & Îles', 'Terrain', 'La Californie'], 'https://www.agencerossicroisette.com/vente/1-cannes/villa/143-a-vendre-villa-californie-6-chambres-terrain-piscine-vue-panoramique-mer-et-iles-de-lerins', 'grad-4', true),
(142, 'Appartement', 4, 3, 100, 'Cannes', 'Palm Beach', 1980000, '4 pièces Palm Beach — 100 m², Parking & Cave', 'Magnifique 4 pièces de 100 m² dans le prestigieux quartier du Palm Beach, à deux pas des plages. Entièrement refait à neuf, vaste séjour avec cuisine ouverte.', ARRAY['100 m²', 'Palm Beach', 'Parking', 'Cave', 'Vue mer'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/142-a-vendre-cannes-secteur-palm-beach-vue-mer-4-pieces-parking-cave', 'grad-5', false),
(141, 'Appartement', 2, 1, 53.38, 'Cannes', 'La Croisette', 1590000, '2 pièces Croisette — 6ème Étage, Face Mer & Palais', 'Au 6e étage d\'une résidence d\'exception sur le boulevard de la Croisette. Rénové avec des matériaux de luxe. Vue sur la mer Méditerranée et le Palais des Festivals.', ARRAY['6ème étage', 'Face mer & Palais', 'Luxe', 'Croisette'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/141-croisette-2p-6eme-face-mer-et-palais', 'grad-6', true),
(140, 'Villa', 10, 7, 321, 'Mougins', 'Mougins', 1380000, 'Villa de Caractère 321 m² — Terrain 1 100 m²', 'Dans un environnement calme et verdoyant, propriété atypique de 370 m² sur terrain plat et arboré de 1 100 m². Cadre de vie rare à deux pas de Mougins.', ARRAY['321 m²', 'Terrain 1100m²', 'Calme', 'Mougins', 'Caractère'], 'https://www.agencerossicroisette.com/vente/10-mougins/villa/140-mougins-villa-de-caractere-370-m-au-coeur-d-un-ecrin-de-verdure', 'grad-1', false),
(139, 'Appartement', 3, 2, 85.59, 'Cannes', 'Basse Californie', 869200, '3 pièces Basse Californie — Piscine, Terrasse 25 m²', 'Dans le quartier prisé de la Basse Californie, superbe 3 pièces de 86 m² niché au calme d\'une impasse piétonne. Résidence récente avec piscine, terrasse de 25 m².', ARRAY['Piscine', 'Terrasse 25m²', 'Calme', 'Récent'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/139-basse-californie-3p-86-m-piscine-terrasse-de-25-m', 'grad-2', false),
(138, 'Appartement', 2, 1, 53.57, 'Cannes', 'Palm Beach', 443000, '2 pièces Croisette — 2 min Plage & Port Canto', 'À seulement 2 minutes de la plage Bijou et du Port Canto. Rez-de-jardin sur la Croisette Palm Beach avec emplacement privilégié.', ARRAY['Rez-de-jardin', '2 min plage', 'Port Canto', 'Croisette'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/138-2p-53m-croisette-palm-beach-2-mn-plage-et-port-canto', 'grad-3', false),
(137, 'Appartement', 2, 2, 60.03, 'Cannes', 'Basse Californie', 593600, '2 pièces Basse Californie — Terrasse, Cave, Meublé', 'Au cœur de la Basse Californie, à deux pas de la Croisette. Entièrement rénové avec goût et vendu meublé. 2ème étage, copropriété de 18 lots.', ARRAY['Meublé', 'Terrasse', 'Cave', 'Rénové', 'Basse Californie'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/137-a-vendre-3-pieces-basse-californie-terrasse-cave-renove', 'grad-4', false),
(133, 'Appartement', 2, 1, 34.7, 'Cannes', 'Basse Californie', 297000, '2 pièces Basse Californie — Rénové, Terrasse', 'Idéalement situé dans la Basse Californie, à quelques pas de la Croisette et de l\'Hôtel Martinez. 2 pièces climatisé de 35 m² avec terrasse.', ARRAY['Terrasse', 'Climatisation', 'Rénové', 'Proche Martinez'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/133-a-vendre-cannes-basse-californie-2p-renove-terrasse', 'grad-5', false),
(132, 'Appartement', 3, 1, 93, 'Cannes', 'La Croisette', 2500000, '3 pièces Le Miramar — Croisette, Vue Mer & Terrasse', 'Au cœur de la Croisette, au sein du Miramar. Appartement de 93 m² face à la mer. 1er étage, vue panoramique sur la Méditerranée, grande terrasse.', ARRAY['Le Miramar', 'Vue mer', 'Terrasse', 'Croisette', '93 m²'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/132-a-vendre-cannes-croisette-miramar-3-pieces-terrasse', 'grad-6', true),
(131, 'Appartement', 2, 1, 32.74, 'Cannes', 'Cannes', 315000, '2 pièces Vue Mer — Rénové, Meublé, Cave & Parking', 'Au 1er étage d\'une copropriété sécurisée de 80 lots, appartement entièrement rénové et vendu meublé. Vue mer, cave, parking, tennis et pétanque.', ARRAY['Vue mer', 'Meublé', 'Cave', 'Parking', 'Tennis'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/131-a-vendre-2-pieces-vue-mer-renove-cave-parking-tennis-petanque', 'grad-1', false),
(130, 'Appartement', 2, 1, 54.56, 'Mandelieu-la-Napoule', 'Mandelieu', 283000, '2 pièces Mandelieu — Jardin 500 m² & Parking', 'Proche des accès autoroutiers et commodités, appartement atypique avec extérieur de 500 m². Entrée sur séjour avec cuisine ouverte.', ARRAY['Jardin 500m²', 'Parking', 'Mandelieu', 'Atypique'], 'https://www.agencerossicroisette.com/vente/150-mandelieu-la-napoule/appartement/130-a-vendre-2-p-mandelieu-jardin-500m2-parking', 'grad-2', false),
(129, 'Appartement', 3, 2, 127, 'Cannes', 'La Croisette', 3600000, '3 pièces Croisette — 127 m², Rénové Luxueux', 'Au cœur de la Croisette, entièrement rénové. Cadre de vie luxueux et raffiné. Beaux volumes, élégante entrée menant à un double séjour.', ARRAY['127 m²', 'Croisette', 'Luxueux', 'Double séjour'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/129-cannes-croisette-appartement-3-pieces-a-vendre', 'grad-3', true),
(128, 'Appartement', 4, 3, 121.36, 'Cannes', 'La Croisette', 4095000, 'Le Relais de la Reine — 4 pièces Croisette Prestige', 'Dans une célébre résidence de standing, magnifique 4 pièces à vendre entièrement rénové en étage élevé. Traversant de 121.36 m², exposé plein SUD, double séjour lumineux.', ARRAY['Plein SUD', 'Étage élevé', 'Traversant', '121 m²', 'Prestige'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/128-a-vendre-cannes-croisette-le-relais-de-la-reine-4-pieces-121m2-prestige', 'grad-4', true),
(126, 'Appartement', 2, 1, 41, 'Cannes', 'Montfleury', 349000, '2 pièces Rez-de-Jardin — Terrasse & Parking', 'Secteur Montfleury, dans une copropriété de standing. Beau 2 pièces en rez-de-jardin avec séjour, cuisine ouverte donnant sur terrasse et jardin privatif.', ARRAY['Rez-de-jardin', 'Terrasse', 'Jardin', 'Parking', 'Standing'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/126-a-vendre-cannes-2-pieces-rez-de-jardin-parking', 'grad-5', false),
(123, 'Appartement', 3, 2, 40, 'Cannes', 'Centre-Ville', 440000, '3 pièces Centre Cannes — Vue Port & Palais', 'Au 4ᵉ étage, vue dégagée sur le port et le Palais des Festivals. Excellent ensoleillement. Séjour lumineux au cœur de Cannes.', ARRAY['Vue port & Palais', '4ème étage', 'Ensoleillé', 'Centre Cannes'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/123-a-vendre-appartement-3-pieces-au-coeur-de-cannes', 'grad-6', false),
(122, 'Rez de jardin', 3, 2, 70.79, 'Villeneuve-Loubet', 'Villeneuve-Loubet', 1200000, 'Rez-de-Jardin Pieds dans l\'Eau — 3 pièces Standing', 'Superbe T3 en rez-de-jardin dans une résidence récente de grand standing, les pieds dans l\'eau. Emplacement exceptionnel alliant confort, élégance et sérénité.', ARRAY['Pieds dans l\'eau', 'Grand standing', 'Récent', 'Vue mer'], 'https://www.agencerossicroisette.com/vente/199-villeneuve-loubet/rez-de-jardin/122-acces-plage-direct-bien-a-vendre-en-residence-recente', 'grad-1', true),
(118, 'Appartement', 1, 0, 21.39, 'Cannes', 'Palm Beach', 260000, 'Studio Palm Beach — Rénové, Terrasse, Cave', 'Secteur Palm Beach, à deux pas des plages. Superbe studio entièrement rénové alliant confort et modernité. Cave incluse.', ARRAY['Palm Beach', 'Terrasse', 'Cave', 'Rénové', 'Proche plages'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/118-cannes-palm-beach-studio-terrasse-cave-ouest-renove', 'grad-2', false),
(116, 'Appartement', 3, 2, 68.5, 'Cannes', 'Centre-Ville', 615000, '3 pièces Meublé — Résidence Standing, Gardien', 'Plein centre de Cannes, proche Croisette et plages. 3 pièces rénové et meublé dans une résidence de standing with gardien. Grande terrasse.', ARRAY['Meublé', 'Gardien', 'Grande terrasse', 'Standing'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/116-cannes-banane-3-pieces', 'grad-3', false),
(115, 'Appartement', 3, 2, 61.16, 'Cannes', 'Arrière-Croisette', 520000, '3 pièces Arrière-Croisette — Garage & Cave', 'Proche centre-ville, des plages et commerces, au calme absolu dans une très belle résidence with gardien. 3 pièces traversant with terrasse de 11 m².', ARRAY['Terrasse 11m²', 'Garage', 'Cave', 'Gardien', 'Calme'], 'https://www.agencerossicroisette.com/vente/1-cannes/appartement/115-cannes-arriere-croisette-3-pces-garage-cave', 'grad-4', false)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    rooms = EXCLUDED.rooms,
    bedrooms = EXCLUDED.bedrooms,
    surface = EXCLUDED.surface,
    city = EXCLUDED.city,
    quartier = EXCLUDED.quartier,
    price = EXCLUDED.price,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    highlights = EXCLUDED.highlights,
    url = EXCLUDED.url,
    gradient = EXCLUDED.gradient,
    prestige = EXCLUDED.prestige,
    updated_at = NOW();
